DEBUG    urllib3.connectionpool:connectionpool.py:232 Starting new HTTP connection (1): 127.0.0.1:6666
DEBUG    urllib3.connectionpool:connectionpool.py:465 http://127.0.0.1:6666 "POST /business/token_login HTTP/1.1" 200 130
DEBUG    urllib3.connectionpool:connectionpool.py:232 Starting new HTTP connection (1): 127.0.0.1:6666
DEBUG    urllib3.connectionpool:connectionpool.py:465 http://127.0.0.1:6666 "POST /business/token_login HTTP/1.1" 200 126
DEBUG    urllib3.connectionpool:connectionpool.py:232 Starting new HTTP connection (1): 127.0.0.1:6666
DEBUG    urllib3.connectionpool:connectionpool.py:465 http://127.0.0.1:6666 "POST /business/token_login HTTP/1.1" 200 130
DEBUG    urllib3.connectionpool:connectionpool.py:232 Starting new HTTP connection (1): 127.0.0.1:6666
DEBUG    urllib3.connectionpool:connectionpool.py:465 http://127.0.0.1:6666 "POST /business/goods_input HTTP/1.1" 200 49
ERROR    root:test_business_token_goods_input01.py:74 测试编号4，测试标题测试商品信息录入—上一次token值，执行失败，实际结果为{'code': 1013, 'msg': '产品名称不能重复'}
ERROR    root:test_business_token_goods_input01.py:75 assert {'code': 1011...请检查token是否失效'} == {'code': 1013...': '产品名称不能重复'}
  Differing items:
  {'msg': '鉴权失败,请检查token是否失效'} != {'msg': '产品名称不能重复'}
  {'code': 1011} != {'code': 1013}
  Full diff:
  - {'code': 1013, 'msg': '产品名称不能重复'}
  + {'code': 1011, 'msg': '鉴权失败,请检查token是否失效'}
Traceback (most recent call last):
  File "D:\PythonWorkSpace\autotest\testcases\test_business_token_goods_input06\test_business_token_goods_input01.py", line 67, in test_goods_input
    assert eval(case.expect) == res
AssertionError: assert {'code': 1011...请检查token是否失效'} == {'code': 1013...': '产品名称不能重复'}
  Differing items:
  {'msg': '鉴权失败,请检查token是否失效'} != {'msg': '产品名称不能重复'}
  {'code': 1011} != {'code': 1013}
  Full diff:
  - {'code': 1013, 'msg': '产品名称不能重复'}
  + {'code': 1011, 'msg': '鉴权失败,请检查token是否失效'}